adding logging

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,6 +22,11 @@ jobs:
           restore-keys: |
               astro-cache-${{ hashFiles('**/package-lock.json') }}
 
+      - name: Debug Build Context
+        run: |
+          echo "Checking files in build context..."
+          ls -la .astro-cache || echo ".astro-cache not found"
+          ls -la
 
       # Step 4: Build the Docker Image
       - name: Build Docker Image with Cache Volume
